# Generated by Django 3.2.12 on 2022-03-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='имя бренда')),
            ],
        ),
        migrations.CreateModel(
            name='GroupItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='группа товара')),
            ],
        ),
        migrations.CreateModel(
            name='Metarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='материал')),
            ],
        ),
        migrations.CreateModel(
            name='SizeDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='диаметр спиц')),
            ],
        ),
        migrations.CreateModel(
            name='SizeNeedle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='размер спицы')),
            ],
        ),
        migrations.CreateModel(
            name='SizeСable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='размер лески')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='тип инструмента')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='количество')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('seoDescription', models.TextField(blank=True, verbose_name='SEO text')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='активно')),
                ('Tags', models.ManyToManyField(blank=True, null=True, related_name='теги', to='toolsKniting.Tags')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toolsKniting.brand', verbose_name='бренд')),
                ('groupItems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='toolsKniting.groupitems', verbose_name='группа товара')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toolsKniting.metarial', verbose_name='материал')),
                ('sizeDiameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toolsKniting.sizediameter', verbose_name='диаметр спиц')),
                ('sizeNeedle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toolsKniting.sizeneedle', verbose_name='размер спицы')),
                ('sizeСable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toolsKniting.sizeсable', verbose_name='размер лески')),
                ('typeTool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toolsKniting.typetool', verbose_name='тип инструмента')),
            ],
        ),
        migrations.AddField(
            model_name='tags',
            name='title',
            field=models.ManyToManyField(max_length=50, to='toolsKniting.Tools', verbose_name='имя тега'),
        ),
    ]
