# Generated by Django 3.2.12 on 2022-03-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsKniting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupitems',
            name='imageGroup',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tools',
            name='imageTool',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
